# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Saleae.Logic2
PackageVersion: 2.4.14
PackageLocale: en-US
Publisher: Saleae Inc
PackageName: Logic 2
License: MIT License
Copyright: Copyright (C) 2024 Saleae Inc
ShortDescription: Saleae Logic 2 Installer
ManifestType: defaultLocale
ManifestVersion: 1.6.0
